import 'package:flutter/material.dart';

IconData iconFromName(String name) {
  const map = {
    'auto_awesome': Icons.auto_awesome,
    'bolt': Icons.bolt,
    'flag': Icons.flag,
    'emoji_events': Icons.emoji_events,
    'psychology': Icons.psychology,
    'timer': Icons.timer,
    'target': Icons.track_changes,
    'track_changes': Icons.track_changes,
    'rocket': Icons.rocket_launch,
    'directions_run': Icons.directions_run,
    'speed': Icons.speed,
    'swap_horiz': Icons.swap_horiz,
    'calendar_view_day': Icons.calendar_view_day,
    'event_available': Icons.event_available,
    'grid_view': Icons.grid_view,
    'apps': Icons.apps,
    'design_services': Icons.design_services,
    'workspace_premium': Icons.workspace_premium,
    'show_chart': Icons.show_chart,
    'timeline': Icons.timeline,
    'electric_bolt': Icons.electric_bolt,
    'flare': Icons.flare,
    'shuffle': Icons.shuffle,
    'offline_bolt': Icons.offline_bolt,
    'lightbulb': Icons.lightbulb,
    'check_circle': Icons.check_circle,
    'task_alt': Icons.task_alt,
    'favorite': Icons.favorite,
    'stairs': Icons.stairs,
    'hourglass_bottom': Icons.hourglass_bottom,
    'architecture': Icons.architecture,
    'menu_book': Icons.menu_book,
    'wb_sunny': Icons.wb_sunny,
    'nightlight_round': Icons.nightlight_round,
    'calendar_month': Icons.calendar_month,
    'star': Icons.star,
    'book': Icons.menu_book,
    'school': Icons.school,
    'local_fire_department': Icons.local_fire_department,
  };
  return map[name] ?? Icons.stars;
}
