name: 'publish'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for arm64 & x64
            args: '--target universal-apple-darwin'
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only needed on MacOS
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install frontend dependencies
        run: npm ci
        shell: bash

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'StudyTracker v__VERSION__'
          releaseBody: 'See the assets below to download the latest version of StudyTracker.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  publish-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: |
          cd study_tracker_flutter
          flutter pub get
      - name: Make gradlew executable
        run: chmod +x study_tracker_flutter/android/gradlew
      - name: Build APK
        run: |
          cd study_tracker_flutter
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: studytracker-android-apk
          path: study_tracker_flutter/build/app/outputs/flutter-apk/app-release.apk
